services:

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - "${VOLUME_BASE_PATH}/pgadmin:/var/lib/pgadmin"
    ports:
      - "5050:80"
    networks:
      - dev_network

  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - "${VOLUME_BASE_PATH}/elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    networks:
      - dev_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q 'status\":\"\\(green\\|yellow\\)'"]
      interval: 30s
      timeout: 30s
      retries: 3

  kibana:
    image: kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - "${VOLUME_BASE_PATH}/kibana:/usr/share/kibana/data"
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - dev_network


  nifi:
    image: apache/nifi:1.24.0
    container_name: nifi
    ports:
      - "9300:9300"
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_WEB_HTTP_PORT}
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
    volumes:
      - "${VOLUME_BASE_PATH}/nifi/database_repository:/opt/nifi/nifi-current/database_repository"
      - "${VOLUME_BASE_PATH}/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository"
      - "${VOLUME_BASE_PATH}/nifi/content_repository:/opt/nifi/nifi-current/content_repository"
      - "${VOLUME_BASE_PATH}/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository"
      - "${VOLUME_BASE_PATH}/nifi/state:/opt/nifi/nifi-current/state"
#      - "${VOLUME_BASE_PATH}/nifi/conf:/opt/nifi/nifi-current/conf"
      - "${VOLUME_BASE_PATH}/nifi/drivers:/opt/nifi/nifi-current/drivers"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge